/*
 * Attributify Mode
 * https://windicss.org/features/attributify.html
 */

module.exports = attributifyRules = [
	/([a-zA-Z]*[=:-]*)?align\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?animate\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?backdrop\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?bg\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?border\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?box\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?container\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?content\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?display\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?cursor\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?filter\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?flex\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?font\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?gap\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?grid\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?justify\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?list\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?opacity\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?order\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?outline\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?overflow\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?ring\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?select\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?shadow\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?space\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?table\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?text\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?transform\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?transition\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?underline\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?rounded\s*[=:-]\s*["']/g,
	/([a-zA-Z]+)?(?<![abcdetuor-])([=:-]+)?h\s*[=:-]\s*["']/g,
	/([a-zA-Z]+)?(?<![abcdetuor-])([=:-]+)?m\s*[=:-]\s*["']/g,
	/([a-zA-Z]+)?(?<![abcdetuor-])([=:-]+)?p\s*[=:-]\s*["']/g,
	/([a-zA-Z]+)?(?<![abcdetuor-])([=:-]+)?w\s*[=:-]\s*["']/g,
	/([a-zA-Z]+)?(?<![abcdetuor-])([=:-]+)?z\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?sm\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?md\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?lg\s*[=:-]\s*["']/g,
	/([a-zA-Z]*[=:-]*)?[0-9]*xl\s*[=:-]\s*["']/g
]
